name: mira_assembler
owner: peterjc
homepage_url: https://github.com/peterjc/pico_galaxy/tools/mira3/
remote_repository_url: https://github.com/peterjc/pico_galaxy/tools/mira3/
description: Assemble with MIRA v3. Takes Sanger, Roche, and Illumina data
long_description: |
  Wrapper for core functionality of assembly tool MIRA 3.4.

  Sanger capillary, Roche 454, Ion Torrent and Solexa/Illumina data,
  and reference backbone sequences are all accepted as inputs.

  The key MIRA output files are captured, but the other files are
  deleted when the job finishes.

  WARNING: This was written to write viral genome assembly and mapping
  pipelines within Galaxy, and while it should work for larger organisms
  like bacteria, the computational load would be much higher. Proceed with
  caution!
categories:
- Assembly
- Next Gen Mappers
type: unrestricted
include:
- strip_components: 2
  source:
  - ../../test-data/empty_file.dat
  - ../../test-data/tvc_contigs.fasta
  - ../../test-data/tvc_mini.fastq
  - ../../tools/mira3/README.rst
  - ../../tools/mira3/mira.py
  - ../../tools/mira3/mira.xml
  - ../../tools/mira3/tool_dependencies.xml
